run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  go: "1.21"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/platformbuilds/mirador-core
  mnd:
    checks: [argument,case,condition,operation,return,assign]
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  unparam:
    check-exported: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - err113
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - lll
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocognit
        - unparam
        - lll
        - errcheck
    - path: internal/api/handlers\.go
      linters:
        - lll
    - path: internal/config/
      linters:
        - goconst
        - depguard
        - err113
        - gosec
        - errcheck
    - path: internal/models/
      linters:
        - mnd
    - path: internal/services/
      linters:
        - mnd
        - unparam
        - err113
        - exhaustive
        - gocritic
        - gosimple
        - ineffassign
        - depguard
        - goimports
        - govet
        - lll
        - gocyclo
        - misspell
        - predeclared
        - unused
        - goconst
        - gosec
        - unconvert
        - staticcheck
    - path: internal/utils/
      linters:
        - mnd
        - depguard
        - err113
        - errcheck
        - gosec
        - gocritic
        - lll
        - unparam
        - gocyclo
        - goconst
        - staticcheck
        - goimports
    - path: pkg/
      linters:
        - mnd
        - depguard
        - err113
        - gocritic
        - errcheck
    - path: internal/repo/
      linters:
        - depguard
        - err113
        - gocritic
        - mnd
        - errcheck
        - unused
        - gosec
        - exhaustive
        - dupl
        - unparam
    - path: internal/api/
      linters:
        - mnd
        - depguard
        - gocritic
        - errcheck
        - err113
        - bodyclose
        - unparam
    - path: internal/models/
      linters:
        - mnd
        - err113
        - gocritic
        - depguard
    - path: internal/api/websocket/
      linters:
        - depguard
        - errcheck
    - path: cmd/
      linters:
        - mnd
        - errcheck
        - gosec
        - err113
        - gocritic
    - path: tools/
      linters:
        - mnd
        - unparam
        - gocyclo
        - gosec
    - path: internal/repo/rbac/weaviate_repository\.go
      linters:
        - dupl
    - path: internal/api/handlers/unified_query\.go
      linters:
        - dupl
    - path: cmd/schemactl/main\.go
      linters:
        - dupl
    - path: internal/models/correlation_query\.go
      linters:
        - dupl
    - path: internal/models/unified_query_language\.go
      linters:
        - dupl
        - unparam
    - path: pkg/cache/valkey_cluster\.go
      linters:
        - dupl
    - path: pkg/cache/valkey_single\.go
      linters:
        - dupl
    - path: internal/api/middleware/search_throttling\.middleware\.go
      linters:
        - dupl
    - path: internal/api/middleware/
      linters:
        - unparam
        - err113
        - gocritic
        - depguard
        - gosec
    - path: internal/services/
      linters:
        - unparam
    - path: internal/utils/bleve/
      linters:
        - predeclared
    - path: internal/config/
      linters:
        - gocyclo
        - mnd
        - gocritic
        - goimports
        - govet
    - path: internal/grpc/
      linters:
        - mnd
        - lll
        - goimports
    - path: internal/monitoring/
      linters:
        - goconst
        - depguard
        - gocritic
    - path: internal/metrics/
      linters:
        - depguard
    - path: internal/storage/weaviate/
      linters:
        - depguard
        - errcheck
        - err113
        - gocritic
        - mnd
        - goimports
        - gofmt
        - gocyclo
    - path: internal/tracing/
      linters:
        - depguard
    - path: internal/discovery/
      linters:
        - depguard
    - path: dev/
      linters:
        - depguard
        - mnd
        - errcheck
        - gosec
    - path: cmd/
      linters:
        - lll
        - depguard
        - gocyclo
    - path: internal/repo/rbac/
      linters:
        - lll
        - goconst
        - gocyclo
        - gofmt
        - goimports
        - govet
    - path: internal/utils/bleve/
      linters:
        - goimports
        - gofmt
        - unused
        - exhaustive
        - gocyclo
        - ineffassign
        - govet
    - path: internal/utils/lucene/
      linters:
        - gocyclo
        - unused
        - exhaustive
        - predeclared
        - goconst
    - path: internal/utils/loadtest/
      linters:
        - misspell
    - path: pkg/cache/
      linters:
        - goimports
        - gofmt
        - gocyclo
        - govet
        - misspell
        - predeclared
    - path: pkg/auth/
      linters:
        - goimports
        - gofmt
        - govet
    - path: internal/models/
      linters:
        - gocyclo
        - goconst
        - misspell
    - path: internal/api/websocket/
      linters:
        - gosec
        - goimports
        - gofmt
    - path: internal/api/handlers/
      linters:
        - dupl
        - goconst
        - gocyclo
        - gosec
        - unused
        - goimports
        - govet
        - lll
        - mnd
        - predeclared
        - misspell
    - path: internal/utils/
      linters:
        - lll
        - unparam
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - staticcheck
      text: "SA1019:" # Using a deprecated function, field, or method
    - linters:
        - staticcheck
      text: "SA1029:" # Using built-in type as context key
    - linters:
        - staticcheck
      text: "SA9003:" # Empty branch
    - linters:
        - staticcheck
      text: "SA6002:" # Argument should be pointer-like
    - linters:
        - stylecheck
      text: "ST1005:" # Error strings should not be capitalized
    - linters:
        - stylecheck  
      text: "ST1023:" # Should omit type from declaration
    - linters:
        - revive
      text: "exported:.*(comment|should have comment)"
    - linters:
        - whitespace
      text: "unnecessary.*(leading|trailing) newline"
    - linters:
        - errcheck
      text: "Error return value of `prometheus\\.Register` is not checked"
    - path: _test\.go
      linters:
        - mnd
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false