version: "2"
run:
  go: "1.21"
  issues-exit-code: 1
  tests: true
output:
  formats:
    text:
      path: stdout
linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - err113
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - misspell
    - mnd
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - unconvert
    - unparam
    - whitespace
  disable:
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - lll
    - nestif
    - prealloc
    - testpackage
    - wsl
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
    depguard:
      rules:
        Main:
          deny:
            - pkg: "github.com/platformbuilds/mirador-core/pkg/logger"
              desc: "Logger should not be imported from pkg; use internal/logging instead"
            - pkg: "github.com/platformbuilds/mirador-core/internal/models"
              desc: "Models should not be imported directly in certain packages"
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    lll:
      line-length: 140
    misspell:
      locale: US  # Use US English for code (standard in Go ecosystem)
    mnd:
      checks:
        - argument
        - case
        - condition
        - operation
        - return
        - assign
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
    revive:
      rules:
        - name: exported
          arguments:
            - disableStutteringCheck
          severity: warning
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1000
        - -ST1003
        - -ST1016
        - -ST1020
        - -ST1021
        - -ST1022
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - funlen
          - gocognit
          - lll
          - mnd
          - unparam
        path: _test\.go
      - linters:
          - lll
        path: internal/api/handlers\.go
      - linters:
          - depguard
          - err113
          - errcheck
          - goconst
          - gosec
        path: internal/config/
      - linters:
          - mnd
        path: internal/models/
      - linters:
          - depguard
          - err113
          - exhaustive
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - misspell
          - mnd
          - predeclared
          - staticcheck
          - unconvert
          - unparam
          - unused
        path: internal/services/
      - linters:
          - depguard
          - err113
          - exhaustive
          - goconst
          - gocritic
          - gocyclo
          - govet
          - ineffassign
          - mnd
          - nolintlint
          - predeclared
          - staticcheck
          - unparam
        path: internal/rca/
      - linters:
          - depguard
          - err113
          - errcheck
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - lll
          - mnd
          - staticcheck
          - unparam
        path: internal/utils/
      - linters:
          - depguard
          - err113
          - errcheck
          - gocritic
          - mnd
        path: pkg/
      - linters:
          - depguard
          - dupl
          - err113
          - errcheck
          - exhaustive
          - gocritic
          - gosec
          - mnd
          - unparam
          - unused
        path: internal/repo/
      - linters:
          - bodyclose
          - depguard
          - err113
          - errcheck
          - gocritic
          - mnd
          - unparam
        path: internal/api/
      - linters:
          - depguard
          - err113
          - gocritic
          - mnd
        path: internal/models/
      - linters:
          - depguard
          - errcheck
        path: internal/api/websocket/
      - linters:
          - err113
          - errcheck
          - gocritic
          - gosec
          - mnd
        path: cmd/
      - linters:
          - exhaustive
          - goconst
          - mnd
          - unparam
          - unused
        path: cmd/otel-fintrans-simulator/
      - linters:
          - gocyclo
          - gosec
          - mnd
          - unparam
        path: tools/
      - linters:
          - depguard
          - err113
          - gocritic
          - mnd
        path: scripts/
      - linters:
          - dupl
        path: internal/repo/rbac/weaviate_repository\.go
      - linters:
          - dupl
        path: internal/api/handlers/unified_query\.go
      - linters:
          - dupl
        path: cmd/schemactl/main\.go
      - linters:
          - dupl
        path: internal/models/correlation_query\.go
      - linters:
          - dupl
          - unparam
        path: internal/models/unified_query_language\.go
      - linters:
          - dupl
        path: pkg/cache/valkey_cluster\.go
      - linters:
          - dupl
        path: pkg/cache/valkey_single\.go
      - linters:
          - dupl
        path: internal/api/middleware/search_throttling\.middleware\.go
      - linters:
          - depguard
          - err113
          - gocritic
          - gocyclo
          - gosec
          - unparam
        path: internal/api/middleware/
      - linters:
          - unparam
        path: internal/services/
      - linters:
          - predeclared
        path: internal/utils/bleve/
      - linters:
          - gocritic
          - gocyclo
          - govet
          - mnd
        path: internal/config/
      - linters:
          - lll
          - mnd
        path: internal/grpc/
      - linters:
          - depguard
          - goconst
          - gocritic
        path: internal/monitoring/
      - linters:
          - depguard
        path: internal/metrics/
      - linters:
          - depguard
          - err113
          - errcheck
          - gocritic
          - gocyclo
          - mnd
        path: internal/storage/weaviate/
      - linters:
          - depguard
        path: internal/tracing/
      - linters:
          - depguard
        path: internal/logging/
      - linters:
          - depguard
        path: internal/discovery/
      - linters:
          - depguard
          - errcheck
          - gosec
          - mnd
        path: dev/
      - linters:
          - depguard
          - gocyclo
          - lll
        path: cmd/
      - linters:
          - goconst
          - gocyclo
          - govet
          - lll
        path: internal/repo/rbac/
      - linters:
          - exhaustive
          - gocyclo
          - govet
          - ineffassign
          - unused
        path: internal/utils/bleve/
      - linters:
          - exhaustive
          - goconst
          - gocyclo
          - predeclared
          - unused
        path: internal/utils/lucene/
      - linters:
          - misspell
        path: internal/utils/loadtest/
      - linters:
          - gocyclo
          - govet
          - misspell
          - predeclared
        path: pkg/cache/
      - linters:
          - govet
        path: pkg/auth/
      - linters:
          - goconst
          - gocyclo
          - misspell
        path: internal/models/
      - linters:
          - gosec
        path: internal/api/websocket/
      - linters:
          - dupl
          - goconst
          - gocyclo
          - gosec
          - govet
          - lll
          - misspell
          - mnd
          - predeclared
          - unused
        path: internal/api/handlers/
      - linters:
          - depguard
          - err113
        path: internal/grpc/clients/
      - linters:
          - depguard
          - gocritic
        path: tools/
      - linters:
          - lll
        source: '^//go:generate '
      - linters:
          - staticcheck
        text: 'SA1019:'
      - linters:
          - staticcheck
        text: 'SA1029:'
      - linters:
          - staticcheck
        text: 'SA9003:'
      - linters:
          - staticcheck
        text: 'SA6002:'
      - linters:
          - staticcheck
        text: 'ST1005:'
      - linters:
          - staticcheck
        text: 'ST1023:'
      - linters:
          - revive
        text: exported:.*(comment|should have comment)
      - linters:
          - whitespace
        text: unnecessary.*(leading|trailing) newline
      - linters:
          - errcheck
        text: Error return value of `prometheus\.Register` is not checked
      - linters:
          - mnd
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/platformbuilds/mirador-core
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - internal/services/
      - internal/utils/
      - internal/config/
      - internal/grpc/
      - internal/storage/weaviate/
      - internal/repo/rbac/
      - internal/utils/bleve/
      - pkg/cache/
      - pkg/auth/
      - internal/api/websocket/
      - internal/api/handlers/
