run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  build-tags: []
  go: "1.21"

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport # https://github.com/go-critic/go-critic/issues/845
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/platformbuilds/mirador-core
  mnd:
    checks: [argument,case,condition,operation,return,assign]
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  lll:
    line-length: 140
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
        arguments:
          - "disableStutteringCheck"
  staticcheck:
    checks: ["all"]
  stylecheck:
    checks: ["all", "-ST1000", "-ST1003", "-ST1016", "-ST1020", "-ST1021", "-ST1022"]
  unparam:
    check-exported: false

linters:
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - depguard
    - dogsled
    - dupl
    - errcheck
    - err113
    - exhaustive
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - funlen
    - gochecknoglobals
    - gocognit
    - godot
    - godox
    - nestif
    - prealloc
    - testpackage
    - wsl

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocognit
        - unparam
        - lll
    - path: internal/api/handlers\.go
      linters:
        - lll
    - path: internal/models/
      linters:
        - mnd
    - path: cmd/
      linters:
        - mnd
    - path: internal/repo/rbac/weaviate_repository\.go
      linters:
        - dupl
    - path: internal/api/handlers/unified_query\.go
      linters:
        - dupl
    - path: cmd/schemactl/main\.go
      linters:
        - dupl
    - linters:
        - lll
      source: "^//go:generate "
    - linters:
        - staticcheck
      text: "SA1019:" # Using a deprecated function, field, or method
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - mnd
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false