# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - echo "Post-create environment setup"
    post_install:
      - echo "Post-install setup"
    pre_build:
      - echo "Pre-build setup"
    post_build:
      - echo "Post-build setup"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false  # Allow warnings during build

# If using MkDocs instead of Sphinx, uncomment this and comment out sphinx above
# mkdocs:
#   configuration: mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
  install:
    - requirements: docs/requirements.txt

# Search configuration
search:
  ranking:
    - title
    - headers
    - content
  ignore:
    - "search.html"
    - "genindex.html"