// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: internal/grpc/proto/predict.proto

package predict

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeFracturesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Component     string                 `protobuf:"bytes,1,opt,name=component,proto3" json:"component,omitempty"`
	TimeRange     string                 `protobuf:"bytes,2,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	ModelTypes    []string               `protobuf:"bytes,3,rep,name=model_types,json=modelTypes,proto3" json:"model_types,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeFracturesRequest) Reset() {
	*x = AnalyzeFracturesRequest{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFracturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFracturesRequest) ProtoMessage() {}

func (x *AnalyzeFracturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFracturesRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFracturesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeFracturesRequest) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *AnalyzeFracturesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *AnalyzeFracturesRequest) GetModelTypes() []string {
	if x != nil {
		return x.ModelTypes
	}
	return nil
}

func (x *AnalyzeFracturesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type AnalyzeFracturesResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Fractures        []*SystemFracture      `protobuf:"bytes,1,rep,name=fractures,proto3" json:"fractures,omitempty"`
	ModelsUsed       []string               `protobuf:"bytes,2,rep,name=models_used,json=modelsUsed,proto3" json:"models_used,omitempty"`
	ProcessingTimeMs int64                  `protobuf:"varint,3,opt,name=processing_time_ms,json=processingTimeMs,proto3" json:"processing_time_ms,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AnalyzeFracturesResponse) Reset() {
	*x = AnalyzeFracturesResponse{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFracturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFracturesResponse) ProtoMessage() {}

func (x *AnalyzeFracturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFracturesResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFracturesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeFracturesResponse) GetFractures() []*SystemFracture {
	if x != nil {
		return x.Fractures
	}
	return nil
}

func (x *AnalyzeFracturesResponse) GetModelsUsed() []string {
	if x != nil {
		return x.ModelsUsed
	}
	return nil
}

func (x *AnalyzeFracturesResponse) GetProcessingTimeMs() int64 {
	if x != nil {
		return x.ProcessingTimeMs
	}
	return 0
}

type SystemFracture struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Component             string                 `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	FractureType          string                 `protobuf:"bytes,3,opt,name=fracture_type,json=fractureType,proto3" json:"fracture_type,omitempty"` // fatigue, overload, degradation
	TimeToFractureSeconds int64                  `protobuf:"varint,4,opt,name=time_to_fracture_seconds,json=timeToFractureSeconds,proto3" json:"time_to_fracture_seconds,omitempty"`
	Severity              string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"` // high, medium, low
	Probability           float64                `protobuf:"fixed64,6,opt,name=probability,proto3" json:"probability,omitempty"`
	Confidence            float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ContributingFactors   []string               `protobuf:"bytes,8,rep,name=contributing_factors,json=contributingFactors,proto3" json:"contributing_factors,omitempty"`
	Recommendation        string                 `protobuf:"bytes,9,opt,name=recommendation,proto3" json:"recommendation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SystemFracture) Reset() {
	*x = SystemFracture{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemFracture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemFracture) ProtoMessage() {}

func (x *SystemFracture) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemFracture.ProtoReflect.Descriptor instead.
func (*SystemFracture) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{2}
}

func (x *SystemFracture) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SystemFracture) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *SystemFracture) GetFractureType() string {
	if x != nil {
		return x.FractureType
	}
	return ""
}

func (x *SystemFracture) GetTimeToFractureSeconds() int64 {
	if x != nil {
		return x.TimeToFractureSeconds
	}
	return 0
}

func (x *SystemFracture) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *SystemFracture) GetProbability() float64 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *SystemFracture) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SystemFracture) GetContributingFactors() []string {
	if x != nil {
		return x.ContributingFactors
	}
	return nil
}

func (x *SystemFracture) GetRecommendation() string {
	if x != nil {
		return x.Recommendation
	}
	return ""
}

type GetFracturesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TimeRange      string                 `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	MinProbability float64                `protobuf:"fixed64,2,opt,name=min_probability,json=minProbability,proto3" json:"min_probability,omitempty"`
	TenantId       string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFracturesRequest) Reset() {
	*x = GetFracturesRequest{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFracturesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFracturesRequest) ProtoMessage() {}

func (x *GetFracturesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFracturesRequest.ProtoReflect.Descriptor instead.
func (*GetFracturesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{3}
}

func (x *GetFracturesRequest) GetTimeRange() string {
	if x != nil {
		return x.TimeRange
	}
	return ""
}

func (x *GetFracturesRequest) GetMinProbability() float64 {
	if x != nil {
		return x.MinProbability
	}
	return 0
}

func (x *GetFracturesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetFracturesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fractures     []*SystemFracture      `protobuf:"bytes,1,rep,name=fractures,proto3" json:"fractures,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFracturesResponse) Reset() {
	*x = GetFracturesResponse{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFracturesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFracturesResponse) ProtoMessage() {}

func (x *GetFracturesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFracturesResponse.ProtoReflect.Descriptor instead.
func (*GetFracturesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{4}
}

func (x *GetFracturesResponse) GetFractures() []*SystemFracture {
	if x != nil {
		return x.Fractures
	}
	return nil
}

type GetModelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsRequest) Reset() {
	*x = GetModelsRequest{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsRequest) ProtoMessage() {}

func (x *GetModelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsRequest.ProtoReflect.Descriptor instead.
func (*GetModelsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{5}
}

func (x *GetModelsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetModelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Models        []*MLModel             `protobuf:"bytes,1,rep,name=models,proto3" json:"models,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelsResponse) Reset() {
	*x = GetModelsResponse{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelsResponse) ProtoMessage() {}

func (x *GetModelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelsResponse.ProtoReflect.Descriptor instead.
func (*GetModelsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{6}
}

func (x *GetModelsResponse) GetModels() []*MLModel {
	if x != nil {
		return x.Models
	}
	return nil
}

type MLModel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Accuracy      float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	LastTrained   string                 `protobuf:"bytes,5,opt,name=last_trained,json=lastTrained,proto3" json:"last_trained,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MLModel) Reset() {
	*x = MLModel{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MLModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLModel) ProtoMessage() {}

func (x *MLModel) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLModel.ProtoReflect.Descriptor instead.
func (*MLModel) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{7}
}

func (x *MLModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MLModel) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MLModel) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MLModel) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *MLModel) GetLastTrained() string {
	if x != nil {
		return x.LastTrained
	}
	return ""
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{8}
}

type GetHealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ModelsActive       int32                  `protobuf:"varint,2,opt,name=models_active,json=modelsActive,proto3" json:"models_active,omitempty"`
	PredictionsPerHour int32                  `protobuf:"varint,3,opt,name=predictions_per_hour,json=predictionsPerHour,proto3" json:"predictions_per_hour,omitempty"`
	Accuracy           float64                `protobuf:"fixed64,4,opt,name=accuracy,proto3" json:"accuracy,omitempty"`
	LastUpdate         string                 `protobuf:"bytes,5,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_predict_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_predict_proto_rawDescGZIP(), []int{9}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetModelsActive() int32 {
	if x != nil {
		return x.ModelsActive
	}
	return 0
}

func (x *GetHealthResponse) GetPredictionsPerHour() int32 {
	if x != nil {
		return x.PredictionsPerHour
	}
	return 0
}

func (x *GetHealthResponse) GetAccuracy() float64 {
	if x != nil {
		return x.Accuracy
	}
	return 0
}

func (x *GetHealthResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

var File_internal_grpc_proto_predict_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_predict_proto_rawDesc = "" +
	"\n" +
	"!internal/grpc/proto/predict.proto\x12\x0fmirador.predict\"\x94\x01\n" +
	"\x17AnalyzeFracturesRequest\x12\x1c\n" +
	"\tcomponent\x18\x01 \x01(\tR\tcomponent\x12\x1d\n" +
	"\n" +
	"time_range\x18\x02 \x01(\tR\ttimeRange\x12\x1f\n" +
	"\vmodel_types\x18\x03 \x03(\tR\n" +
	"modelTypes\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\"\xa8\x01\n" +
	"\x18AnalyzeFracturesResponse\x12=\n" +
	"\tfractures\x18\x01 \x03(\v2\x1f.mirador.predict.SystemFractureR\tfractures\x12\x1f\n" +
	"\vmodels_used\x18\x02 \x03(\tR\n" +
	"modelsUsed\x12,\n" +
	"\x12processing_time_ms\x18\x03 \x01(\x03R\x10processingTimeMs\"\xd5\x02\n" +
	"\x0eSystemFracture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tcomponent\x18\x02 \x01(\tR\tcomponent\x12#\n" +
	"\rfracture_type\x18\x03 \x01(\tR\ffractureType\x127\n" +
	"\x18time_to_fracture_seconds\x18\x04 \x01(\x03R\x15timeToFractureSeconds\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12 \n" +
	"\vprobability\x18\x06 \x01(\x01R\vprobability\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x121\n" +
	"\x14contributing_factors\x18\b \x03(\tR\x13contributingFactors\x12&\n" +
	"\x0erecommendation\x18\t \x01(\tR\x0erecommendation\"z\n" +
	"\x13GetFracturesRequest\x12\x1d\n" +
	"\n" +
	"time_range\x18\x01 \x01(\tR\ttimeRange\x12'\n" +
	"\x0fmin_probability\x18\x02 \x01(\x01R\x0eminProbability\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\"U\n" +
	"\x14GetFracturesResponse\x12=\n" +
	"\tfractures\x18\x01 \x03(\v2\x1f.mirador.predict.SystemFractureR\tfractures\"/\n" +
	"\x10GetModelsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"E\n" +
	"\x11GetModelsResponse\x120\n" +
	"\x06models\x18\x01 \x03(\v2\x18.mirador.predict.MLModelR\x06models\"\x88\x01\n" +
	"\aMLModel\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12!\n" +
	"\flast_trained\x18\x05 \x01(\tR\vlastTrained\"\x12\n" +
	"\x10GetHealthRequest\"\xbf\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\rmodels_active\x18\x02 \x01(\x05R\fmodelsActive\x120\n" +
	"\x14predictions_per_hour\x18\x03 \x01(\x05R\x12predictionsPerHour\x12\x1a\n" +
	"\baccuracy\x18\x04 \x01(\x01R\baccuracy\x12\x1f\n" +
	"\vlast_update\x18\x05 \x01(\tR\n" +
	"lastUpdate2\x8d\x03\n" +
	"\x14PredictEngineService\x12g\n" +
	"\x10AnalyzeFractures\x12(.mirador.predict.AnalyzeFracturesRequest\x1a).mirador.predict.AnalyzeFracturesResponse\x12d\n" +
	"\x15GetPredictedFractures\x12$.mirador.predict.GetFracturesRequest\x1a%.mirador.predict.GetFracturesResponse\x12R\n" +
	"\tGetModels\x12!.mirador.predict.GetModelsRequest\x1a\".mirador.predict.GetModelsResponse\x12R\n" +
	"\tGetHealth\x12!.mirador.predict.GetHealthRequest\x1a\".mirador.predict.GetHealthResponseBDZBgithub.com/platformbuilds/mirador-core/internal/grpc/proto/predictb\x06proto3"

var (
	file_internal_grpc_proto_predict_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_predict_proto_rawDescData []byte
)

func file_internal_grpc_proto_predict_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_predict_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_predict_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_predict_proto_rawDesc), len(file_internal_grpc_proto_predict_proto_rawDesc)))
	})
	return file_internal_grpc_proto_predict_proto_rawDescData
}

var file_internal_grpc_proto_predict_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_internal_grpc_proto_predict_proto_goTypes = []any{
	(*AnalyzeFracturesRequest)(nil),  // 0: mirador.predict.AnalyzeFracturesRequest
	(*AnalyzeFracturesResponse)(nil), // 1: mirador.predict.AnalyzeFracturesResponse
	(*SystemFracture)(nil),           // 2: mirador.predict.SystemFracture
	(*GetFracturesRequest)(nil),      // 3: mirador.predict.GetFracturesRequest
	(*GetFracturesResponse)(nil),     // 4: mirador.predict.GetFracturesResponse
	(*GetModelsRequest)(nil),         // 5: mirador.predict.GetModelsRequest
	(*GetModelsResponse)(nil),        // 6: mirador.predict.GetModelsResponse
	(*MLModel)(nil),                  // 7: mirador.predict.MLModel
	(*GetHealthRequest)(nil),         // 8: mirador.predict.GetHealthRequest
	(*GetHealthResponse)(nil),        // 9: mirador.predict.GetHealthResponse
}
var file_internal_grpc_proto_predict_proto_depIdxs = []int32{
	2, // 0: mirador.predict.AnalyzeFracturesResponse.fractures:type_name -> mirador.predict.SystemFracture
	2, // 1: mirador.predict.GetFracturesResponse.fractures:type_name -> mirador.predict.SystemFracture
	7, // 2: mirador.predict.GetModelsResponse.models:type_name -> mirador.predict.MLModel
	0, // 3: mirador.predict.PredictEngineService.AnalyzeFractures:input_type -> mirador.predict.AnalyzeFracturesRequest
	3, // 4: mirador.predict.PredictEngineService.GetPredictedFractures:input_type -> mirador.predict.GetFracturesRequest
	5, // 5: mirador.predict.PredictEngineService.GetModels:input_type -> mirador.predict.GetModelsRequest
	8, // 6: mirador.predict.PredictEngineService.GetHealth:input_type -> mirador.predict.GetHealthRequest
	1, // 7: mirador.predict.PredictEngineService.AnalyzeFractures:output_type -> mirador.predict.AnalyzeFracturesResponse
	4, // 8: mirador.predict.PredictEngineService.GetPredictedFractures:output_type -> mirador.predict.GetFracturesResponse
	6, // 9: mirador.predict.PredictEngineService.GetModels:output_type -> mirador.predict.GetModelsResponse
	9, // 10: mirador.predict.PredictEngineService.GetHealth:output_type -> mirador.predict.GetHealthResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_predict_proto_init() }
func file_internal_grpc_proto_predict_proto_init() {
	if File_internal_grpc_proto_predict_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_predict_proto_rawDesc), len(file_internal_grpc_proto_predict_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_predict_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_predict_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_predict_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_predict_proto = out.File
	file_internal_grpc_proto_predict_proto_goTypes = nil
	file_internal_grpc_proto_predict_proto_depIdxs = nil
}
