// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: internal/grpc/proto/rca.proto

package rca

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for RCA investigation
type InvestigateRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	IncidentId       string                 `protobuf:"bytes,1,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	Symptoms         []string               `protobuf:"bytes,2,rep,name=symptoms,proto3" json:"symptoms,omitempty"`
	TimeRange        *TimeRange             `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	AffectedServices []string               `protobuf:"bytes,4,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	AnomalyThreshold float64                `protobuf:"fixed64,5,opt,name=anomaly_threshold,json=anomalyThreshold,proto3" json:"anomaly_threshold,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvestigateRequest) Reset() {
	*x = InvestigateRequest{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestigateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestigateRequest) ProtoMessage() {}

func (x *InvestigateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestigateRequest.ProtoReflect.Descriptor instead.
func (*InvestigateRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{0}
}

func (x *InvestigateRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *InvestigateRequest) GetSymptoms() []string {
	if x != nil {
		return x.Symptoms
	}
	return nil
}

func (x *InvestigateRequest) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *InvestigateRequest) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *InvestigateRequest) GetAnomalyThreshold() float64 {
	if x != nil {
		return x.AnomalyThreshold
	}
	return 0
}

// Response from RCA investigation
type InvestigateResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId    string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	RootCause        string                 `protobuf:"bytes,2,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Confidence       float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AffectedServices []string               `protobuf:"bytes,4,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	Timeline         []*TimelineEvent       `protobuf:"bytes,5,rep,name=timeline,proto3" json:"timeline,omitempty"`
	RedAnchors       []*RedAnchor           `protobuf:"bytes,6,rep,name=red_anchors,json=redAnchors,proto3" json:"red_anchors,omitempty"`
	Recommendations  []string               `protobuf:"bytes,7,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InvestigateResponse) Reset() {
	*x = InvestigateResponse{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvestigateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvestigateResponse) ProtoMessage() {}

func (x *InvestigateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvestigateResponse.ProtoReflect.Descriptor instead.
func (*InvestigateResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{1}
}

func (x *InvestigateResponse) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *InvestigateResponse) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *InvestigateResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *InvestigateResponse) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *InvestigateResponse) GetTimeline() []*TimelineEvent {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *InvestigateResponse) GetRedAnchors() []*RedAnchor {
	if x != nil {
		return x.RedAnchors
	}
	return nil
}

func (x *InvestigateResponse) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Anomaly “red anchor”
type RedAnchor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Metric        string                 `protobuf:"bytes,2,opt,name=metric,proto3" json:"metric,omitempty"`
	AnomalyScore  float64                `protobuf:"fixed64,3,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	Threshold     float64                `protobuf:"fixed64,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TimestampUnix int64                  `protobuf:"varint,5,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"` // epoch seconds (or ms if you prefer—keep consistent)
	DataType      string                 `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"`                 // "metrics" | "logs" | "traces"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedAnchor) Reset() {
	*x = RedAnchor{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedAnchor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedAnchor) ProtoMessage() {}

func (x *RedAnchor) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedAnchor.ProtoReflect.Descriptor instead.
func (*RedAnchor) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{2}
}

func (x *RedAnchor) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *RedAnchor) GetMetric() string {
	if x != nil {
		return x.Metric
	}
	return ""
}

func (x *RedAnchor) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *RedAnchor) GetThreshold() float64 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *RedAnchor) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *RedAnchor) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

// Time range
type TimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartUnix     int64                  `protobuf:"varint,1,opt,name=start_unix,json=startUnix,proto3" json:"start_unix,omitempty"`
	EndUnix       int64                  `protobuf:"varint,2,opt,name=end_unix,json=endUnix,proto3" json:"end_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{3}
}

func (x *TimeRange) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *TimeRange) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

// Timeline event in correlation result
type TimelineEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimestampUnix int64                  `protobuf:"varint,1,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	Event         string                 `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	Service       string                 `protobuf:"bytes,3,opt,name=service,proto3" json:"service,omitempty"`
	Severity      string                 `protobuf:"bytes,4,opt,name=severity,proto3" json:"severity,omitempty"`
	AnomalyScore  float64                `protobuf:"fixed64,5,opt,name=anomaly_score,json=anomalyScore,proto3" json:"anomaly_score,omitempty"`
	DataType      string                 `protobuf:"bytes,6,opt,name=data_type,json=dataType,proto3" json:"data_type,omitempty"` // NEW: keep in sync with your client conversion
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimelineEvent) Reset() {
	*x = TimelineEvent{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimelineEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimelineEvent) ProtoMessage() {}

func (x *TimelineEvent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimelineEvent.ProtoReflect.Descriptor instead.
func (*TimelineEvent) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{4}
}

func (x *TimelineEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *TimelineEvent) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TimelineEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *TimelineEvent) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *TimelineEvent) GetAnomalyScore() float64 {
	if x != nil {
		return x.AnomalyScore
	}
	return 0
}

func (x *TimelineEvent) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

// List active correlations
type GetCorrelationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorrelationsRequest) Reset() {
	*x = GetCorrelationsRequest{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorrelationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorrelationsRequest) ProtoMessage() {}

func (x *GetCorrelationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorrelationsRequest.ProtoReflect.Descriptor instead.
func (*GetCorrelationsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{5}
}

func (x *GetCorrelationsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetCorrelationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correlations  []*Correlation         `protobuf:"bytes,1,rep,name=correlations,proto3" json:"correlations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCorrelationsResponse) Reset() {
	*x = GetCorrelationsResponse{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCorrelationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorrelationsResponse) ProtoMessage() {}

func (x *GetCorrelationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorrelationsResponse.ProtoReflect.Descriptor instead.
func (*GetCorrelationsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{6}
}

func (x *GetCorrelationsResponse) GetCorrelations() []*Correlation {
	if x != nil {
		return x.Correlations
	}
	return nil
}

type Correlation struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CorrelationId    string                 `protobuf:"bytes,1,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	RootCause        string                 `protobuf:"bytes,2,opt,name=root_cause,json=rootCause,proto3" json:"root_cause,omitempty"`
	Confidence       float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	AffectedServices []string               `protobuf:"bytes,4,rep,name=affected_services,json=affectedServices,proto3" json:"affected_services,omitempty"`
	Timeline         []*TimelineEvent       `protobuf:"bytes,5,rep,name=timeline,proto3" json:"timeline,omitempty"`
	RedAnchors       []*RedAnchor           `protobuf:"bytes,6,rep,name=red_anchors,json=redAnchors,proto3" json:"red_anchors,omitempty"`
	Recommendations  []string               `protobuf:"bytes,7,rep,name=recommendations,proto3" json:"recommendations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Correlation) Reset() {
	*x = Correlation{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Correlation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Correlation) ProtoMessage() {}

func (x *Correlation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Correlation.ProtoReflect.Descriptor instead.
func (*Correlation) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{7}
}

func (x *Correlation) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

func (x *Correlation) GetRootCause() string {
	if x != nil {
		return x.RootCause
	}
	return ""
}

func (x *Correlation) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Correlation) GetAffectedServices() []string {
	if x != nil {
		return x.AffectedServices
	}
	return nil
}

func (x *Correlation) GetTimeline() []*TimelineEvent {
	if x != nil {
		return x.Timeline
	}
	return nil
}

func (x *Correlation) GetRedAnchors() []*RedAnchor {
	if x != nil {
		return x.RedAnchors
	}
	return nil
}

func (x *Correlation) GetRecommendations() []string {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

// Failure patterns
type GetPatternsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatternsRequest) Reset() {
	*x = GetPatternsRequest{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatternsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatternsRequest) ProtoMessage() {}

func (x *GetPatternsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatternsRequest.ProtoReflect.Descriptor instead.
func (*GetPatternsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{8}
}

func (x *GetPatternsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetPatternsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Patterns      []*FailurePattern      `protobuf:"bytes,1,rep,name=patterns,proto3" json:"patterns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPatternsResponse) Reset() {
	*x = GetPatternsResponse{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPatternsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPatternsResponse) ProtoMessage() {}

func (x *GetPatternsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPatternsResponse.ProtoReflect.Descriptor instead.
func (*GetPatternsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{9}
}

func (x *GetPatternsResponse) GetPatterns() []*FailurePattern {
	if x != nil {
		return x.Patterns
	}
	return nil
}

type FailurePattern struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatternId     string                 `protobuf:"bytes,1,opt,name=pattern_id,json=patternId,proto3" json:"pattern_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Indicators    []string               `protobuf:"bytes,4,rep,name=indicators,proto3" json:"indicators,omitempty"`
	Frequency     float64                `protobuf:"fixed64,5,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailurePattern) Reset() {
	*x = FailurePattern{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailurePattern) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailurePattern) ProtoMessage() {}

func (x *FailurePattern) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailurePattern.ProtoReflect.Descriptor instead.
func (*FailurePattern) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{10}
}

func (x *FailurePattern) GetPatternId() string {
	if x != nil {
		return x.PatternId
	}
	return ""
}

func (x *FailurePattern) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FailurePattern) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FailurePattern) GetIndicators() []string {
	if x != nil {
		return x.Indicators
	}
	return nil
}

func (x *FailurePattern) GetFrequency() float64 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

// Health
type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{11}
}

type GetHealthResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Status             string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveCorrelations int32                  `protobuf:"varint,2,opt,name=active_correlations,json=activeCorrelations,proto3" json:"active_correlations,omitempty"`
	AvgResolutionTime  float64                `protobuf:"fixed64,3,opt,name=avg_resolution_time,json=avgResolutionTime,proto3" json:"avg_resolution_time,omitempty"`
	LastUpdate         string                 `protobuf:"bytes,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_rca_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_rca_proto_rawDescGZIP(), []int{12}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetActiveCorrelations() int32 {
	if x != nil {
		return x.ActiveCorrelations
	}
	return 0
}

func (x *GetHealthResponse) GetAvgResolutionTime() float64 {
	if x != nil {
		return x.AvgResolutionTime
	}
	return 0
}

func (x *GetHealthResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

var File_internal_grpc_proto_rca_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_rca_proto_rawDesc = "" +
	"\n" +
	"\x1dinternal/grpc/proto/rca.proto\x12\vmirador.rca\"\xe2\x01\n" +
	"\x12InvestigateRequest\x12\x1f\n" +
	"\vincident_id\x18\x01 \x01(\tR\n" +
	"incidentId\x12\x1a\n" +
	"\bsymptoms\x18\x02 \x03(\tR\bsymptoms\x125\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x16.mirador.rca.TimeRangeR\ttimeRange\x12+\n" +
	"\x11affected_services\x18\x04 \x03(\tR\x10affectedServices\x12+\n" +
	"\x11anomaly_threshold\x18\x05 \x01(\x01R\x10anomalyThreshold\"\xc3\x02\n" +
	"\x13InvestigateResponse\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x02 \x01(\tR\trootCause\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11affected_services\x18\x04 \x03(\tR\x10affectedServices\x126\n" +
	"\btimeline\x18\x05 \x03(\v2\x1a.mirador.rca.TimelineEventR\btimeline\x127\n" +
	"\vred_anchors\x18\x06 \x03(\v2\x16.mirador.rca.RedAnchorR\n" +
	"redAnchors\x12(\n" +
	"\x0frecommendations\x18\a \x03(\tR\x0frecommendations\"\xc4\x01\n" +
	"\tRedAnchor\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x16\n" +
	"\x06metric\x18\x02 \x01(\tR\x06metric\x12#\n" +
	"\ranomaly_score\x18\x03 \x01(\x01R\fanomalyScore\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x01R\tthreshold\x12%\n" +
	"\x0etimestamp_unix\x18\x05 \x01(\x03R\rtimestampUnix\x12\x1b\n" +
	"\tdata_type\x18\x06 \x01(\tR\bdataType\"E\n" +
	"\tTimeRange\x12\x1d\n" +
	"\n" +
	"start_unix\x18\x01 \x01(\x03R\tstartUnix\x12\x19\n" +
	"\bend_unix\x18\x02 \x01(\x03R\aendUnix\"\xc4\x01\n" +
	"\rTimelineEvent\x12%\n" +
	"\x0etimestamp_unix\x18\x01 \x01(\x03R\rtimestampUnix\x12\x14\n" +
	"\x05event\x18\x02 \x01(\tR\x05event\x12\x18\n" +
	"\aservice\x18\x03 \x01(\tR\aservice\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\tR\bseverity\x12#\n" +
	"\ranomaly_score\x18\x05 \x01(\x01R\fanomalyScore\x12\x1b\n" +
	"\tdata_type\x18\x06 \x01(\tR\bdataType\"5\n" +
	"\x16GetCorrelationsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"W\n" +
	"\x17GetCorrelationsResponse\x12<\n" +
	"\fcorrelations\x18\x01 \x03(\v2\x18.mirador.rca.CorrelationR\fcorrelations\"\xbb\x02\n" +
	"\vCorrelation\x12%\n" +
	"\x0ecorrelation_id\x18\x01 \x01(\tR\rcorrelationId\x12\x1d\n" +
	"\n" +
	"root_cause\x18\x02 \x01(\tR\trootCause\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\x12+\n" +
	"\x11affected_services\x18\x04 \x03(\tR\x10affectedServices\x126\n" +
	"\btimeline\x18\x05 \x03(\v2\x1a.mirador.rca.TimelineEventR\btimeline\x127\n" +
	"\vred_anchors\x18\x06 \x03(\v2\x16.mirador.rca.RedAnchorR\n" +
	"redAnchors\x12(\n" +
	"\x0frecommendations\x18\a \x03(\tR\x0frecommendations\"1\n" +
	"\x12GetPatternsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"N\n" +
	"\x13GetPatternsResponse\x127\n" +
	"\bpatterns\x18\x01 \x03(\v2\x1b.mirador.rca.FailurePatternR\bpatterns\"\xa3\x01\n" +
	"\x0eFailurePattern\x12\x1d\n" +
	"\n" +
	"pattern_id\x18\x01 \x01(\tR\tpatternId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"indicators\x18\x04 \x03(\tR\n" +
	"indicators\x12\x1c\n" +
	"\tfrequency\x18\x05 \x01(\x01R\tfrequency\"\x12\n" +
	"\x10GetHealthRequest\"\xad\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12/\n" +
	"\x13active_correlations\x18\x02 \x01(\x05R\x12activeCorrelations\x12.\n" +
	"\x13avg_resolution_time\x18\x03 \x01(\x01R\x11avgResolutionTime\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\tR\n" +
	"lastUpdate2\xf5\x02\n" +
	"\x10RCAEngineService\x12X\n" +
	"\x13InvestigateIncident\x12\x1f.mirador.rca.InvestigateRequest\x1a .mirador.rca.InvestigateResponse\x12b\n" +
	"\x15GetActiveCorrelations\x12#.mirador.rca.GetCorrelationsRequest\x1a$.mirador.rca.GetCorrelationsResponse\x12W\n" +
	"\x12GetFailurePatterns\x12\x1f.mirador.rca.GetPatternsRequest\x1a .mirador.rca.GetPatternsResponse\x12J\n" +
	"\tGetHealth\x12\x1d.mirador.rca.GetHealthRequest\x1a\x1e.mirador.rca.GetHealthResponseB@Z>github.com/platformbuilds/mirador-core/internal/grpc/proto/rcab\x06proto3"

var (
	file_internal_grpc_proto_rca_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_rca_proto_rawDescData []byte
)

func file_internal_grpc_proto_rca_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_rca_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_rca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_rca_proto_rawDesc), len(file_internal_grpc_proto_rca_proto_rawDesc)))
	})
	return file_internal_grpc_proto_rca_proto_rawDescData
}

var file_internal_grpc_proto_rca_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_internal_grpc_proto_rca_proto_goTypes = []any{
	(*InvestigateRequest)(nil),      // 0: mirador.rca.InvestigateRequest
	(*InvestigateResponse)(nil),     // 1: mirador.rca.InvestigateResponse
	(*RedAnchor)(nil),               // 2: mirador.rca.RedAnchor
	(*TimeRange)(nil),               // 3: mirador.rca.TimeRange
	(*TimelineEvent)(nil),           // 4: mirador.rca.TimelineEvent
	(*GetCorrelationsRequest)(nil),  // 5: mirador.rca.GetCorrelationsRequest
	(*GetCorrelationsResponse)(nil), // 6: mirador.rca.GetCorrelationsResponse
	(*Correlation)(nil),             // 7: mirador.rca.Correlation
	(*GetPatternsRequest)(nil),      // 8: mirador.rca.GetPatternsRequest
	(*GetPatternsResponse)(nil),     // 9: mirador.rca.GetPatternsResponse
	(*FailurePattern)(nil),          // 10: mirador.rca.FailurePattern
	(*GetHealthRequest)(nil),        // 11: mirador.rca.GetHealthRequest
	(*GetHealthResponse)(nil),       // 12: mirador.rca.GetHealthResponse
}
var file_internal_grpc_proto_rca_proto_depIdxs = []int32{
	3,  // 0: mirador.rca.InvestigateRequest.time_range:type_name -> mirador.rca.TimeRange
	4,  // 1: mirador.rca.InvestigateResponse.timeline:type_name -> mirador.rca.TimelineEvent
	2,  // 2: mirador.rca.InvestigateResponse.red_anchors:type_name -> mirador.rca.RedAnchor
	7,  // 3: mirador.rca.GetCorrelationsResponse.correlations:type_name -> mirador.rca.Correlation
	4,  // 4: mirador.rca.Correlation.timeline:type_name -> mirador.rca.TimelineEvent
	2,  // 5: mirador.rca.Correlation.red_anchors:type_name -> mirador.rca.RedAnchor
	10, // 6: mirador.rca.GetPatternsResponse.patterns:type_name -> mirador.rca.FailurePattern
	0,  // 7: mirador.rca.RCAEngineService.InvestigateIncident:input_type -> mirador.rca.InvestigateRequest
	5,  // 8: mirador.rca.RCAEngineService.GetActiveCorrelations:input_type -> mirador.rca.GetCorrelationsRequest
	8,  // 9: mirador.rca.RCAEngineService.GetFailurePatterns:input_type -> mirador.rca.GetPatternsRequest
	11, // 10: mirador.rca.RCAEngineService.GetHealth:input_type -> mirador.rca.GetHealthRequest
	1,  // 11: mirador.rca.RCAEngineService.InvestigateIncident:output_type -> mirador.rca.InvestigateResponse
	6,  // 12: mirador.rca.RCAEngineService.GetActiveCorrelations:output_type -> mirador.rca.GetCorrelationsResponse
	9,  // 13: mirador.rca.RCAEngineService.GetFailurePatterns:output_type -> mirador.rca.GetPatternsResponse
	12, // 14: mirador.rca.RCAEngineService.GetHealth:output_type -> mirador.rca.GetHealthResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_rca_proto_init() }
func file_internal_grpc_proto_rca_proto_init() {
	if File_internal_grpc_proto_rca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_rca_proto_rawDesc), len(file_internal_grpc_proto_rca_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_rca_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_rca_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_rca_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_rca_proto = out.File
	file_internal_grpc_proto_rca_proto_goTypes = nil
	file_internal_grpc_proto_rca_proto_depIdxs = nil
}
