apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector
  namespace: mirador-observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/component: collector
    app.kubernetes.io/part-of: mirador
