apiVersion: v1
kind: Namespace
metadata:
  name: java-profiling
  labels:
    app.kubernetes.io/name: java-profiling
    app.kubernetes.io/component: profiling
    app.kubernetes.io/part-of: mirador-observability
