apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-ebpf-instrument
  namespace: mirador-observability
  labels:
    app.kubernetes.io/name: otel-ebpf-instrument
    app.kubernetes.io/component: instrumentation
    app.kubernetes.io/part-of: mirador
