// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.0
// source: internal/grpc/proto/alert/alert.proto

package alert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessAlertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alert         *Alert                 `protobuf:"bytes,1,opt,name=alert,proto3" json:"alert,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessAlertRequest) Reset() {
	*x = ProcessAlertRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAlertRequest) ProtoMessage() {}

func (x *ProcessAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAlertRequest.ProtoReflect.Descriptor instead.
func (*ProcessAlertRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessAlertRequest) GetAlert() *Alert {
	if x != nil {
		return x.Alert
	}
	return nil
}

func (x *ProcessAlertRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ProcessAlertResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ProcessedAlert *ProcessedAlert        `protobuf:"bytes,1,opt,name=processed_alert,json=processedAlert,proto3" json:"processed_alert,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessAlertResponse) Reset() {
	*x = ProcessAlertResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessAlertResponse) ProtoMessage() {}

func (x *ProcessAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessAlertResponse.ProtoReflect.Descriptor instead.
func (*ProcessAlertResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessAlertResponse) GetProcessedAlert() *ProcessedAlert {
	if x != nil {
		return x.ProcessedAlert
	}
	return nil
}

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Severity      string                 `protobuf:"bytes,2,opt,name=severity,proto3" json:"severity,omitempty"`
	Component     string                 `protobuf:"bytes,3,opt,name=component,proto3" json:"component,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // epoch seconds (or ms if you prefer—keep consistent)
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,7,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{2}
}

func (x *Alert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Alert) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *Alert) GetComponent() string {
	if x != nil {
		return x.Component
	}
	return ""
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Alert) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Alert) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ProcessedAlert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // fire | suppress | escalate | cluster
	ClusterId     string                 `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Escalation    string                 `protobuf:"bytes,4,opt,name=escalation,proto3" json:"escalation,omitempty"`
	Notifications []string               `protobuf:"bytes,5,rep,name=notifications,proto3" json:"notifications,omitempty"` // slack, teams, email, ...
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessedAlert) Reset() {
	*x = ProcessedAlert{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessedAlert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessedAlert) ProtoMessage() {}

func (x *ProcessedAlert) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessedAlert.ProtoReflect.Descriptor instead.
func (*ProcessedAlert) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessedAlert) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProcessedAlert) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ProcessedAlert) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ProcessedAlert) GetEscalation() string {
	if x != nil {
		return x.Escalation
	}
	return ""
}

func (x *ProcessedAlert) GetNotifications() []string {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type GetAlertRulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRulesRequest) Reset() {
	*x = GetAlertRulesRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRulesRequest) ProtoMessage() {}

func (x *GetAlertRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRulesRequest.ProtoReflect.Descriptor instead.
func (*GetAlertRulesRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{4}
}

func (x *GetAlertRulesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetAlertRulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rules         []*AlertRule           `protobuf:"bytes,1,rep,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertRulesResponse) Reset() {
	*x = GetAlertRulesResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertRulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertRulesResponse) ProtoMessage() {}

func (x *GetAlertRulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertRulesResponse.ProtoReflect.Descriptor instead.
func (*GetAlertRulesResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlertRulesResponse) GetRules() []*AlertRule {
	if x != nil {
		return x.Rules
	}
	return nil
}

type AlertRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`         // MetricsQL/LogsQL/Traces
	Condition     string                 `protobuf:"bytes,4,opt,name=condition,proto3" json:"condition,omitempty"` // e.g. "> 0.8"
	Severity      string                 `protobuf:"bytes,5,opt,name=severity,proto3" json:"severity,omitempty"`   // critical/warning/info
	Enabled       bool                   `protobuf:"varint,6,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,7,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,8,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertRule) Reset() {
	*x = AlertRule{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertRule) ProtoMessage() {}

func (x *AlertRule) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertRule.ProtoReflect.Descriptor instead.
func (*AlertRule) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{6}
}

func (x *AlertRule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AlertRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AlertRule) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *AlertRule) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AlertRule) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

func (x *AlertRule) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AlertRule) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *AlertRule) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type CreateAlertRuleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleRequest) Reset() {
	*x = CreateAlertRuleRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleRequest) ProtoMessage() {}

func (x *CreateAlertRuleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleRequest.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{7}
}

func (x *CreateAlertRuleRequest) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

func (x *CreateAlertRuleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type CreateAlertRuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *AlertRule             `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlertRuleResponse) Reset() {
	*x = CreateAlertRuleResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlertRuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlertRuleResponse) ProtoMessage() {}

func (x *CreateAlertRuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlertRuleResponse.ProtoReflect.Descriptor instead.
func (*CreateAlertRuleResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{8}
}

func (x *CreateAlertRuleResponse) GetRule() *AlertRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type GetActiveAlertsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Severity      string                 `protobuf:"bytes,3,opt,name=severity,proto3" json:"severity,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAlertsRequest) Reset() {
	*x = GetActiveAlertsRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertsRequest) ProtoMessage() {}

func (x *GetActiveAlertsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertsRequest.ProtoReflect.Descriptor instead.
func (*GetActiveAlertsRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{9}
}

func (x *GetActiveAlertsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetActiveAlertsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetActiveAlertsRequest) GetSeverity() string {
	if x != nil {
		return x.Severity
	}
	return ""
}

type GetActiveAlertsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Alerts        []*Alert               `protobuf:"bytes,1,rep,name=alerts,proto3" json:"alerts,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveAlertsResponse) Reset() {
	*x = GetActiveAlertsResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveAlertsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveAlertsResponse) ProtoMessage() {}

func (x *GetActiveAlertsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveAlertsResponse.ProtoReflect.Descriptor instead.
func (*GetActiveAlertsResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{10}
}

func (x *GetActiveAlertsResponse) GetAlerts() []*Alert {
	if x != nil {
		return x.Alerts
	}
	return nil
}

func (x *GetActiveAlertsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type AcknowledgeAlertRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlertId        string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	AcknowledgedBy string                 `protobuf:"bytes,2,opt,name=acknowledged_by,json=acknowledgedBy,proto3" json:"acknowledged_by,omitempty"`
	Comment        string                 `protobuf:"bytes,3,opt,name=comment,proto3" json:"comment,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcknowledgeAlertRequest) Reset() {
	*x = AcknowledgeAlertRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertRequest) ProtoMessage() {}

func (x *AcknowledgeAlertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{11}
}

func (x *AcknowledgeAlertRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetAcknowledgedBy() string {
	if x != nil {
		return x.AcknowledgedBy
	}
	return ""
}

func (x *AcknowledgeAlertRequest) GetComment() string {
	if x != nil {
		return x.Comment
	}
	return ""
}

type AcknowledgeAlertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeAlertResponse) Reset() {
	*x = AcknowledgeAlertResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeAlertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeAlertResponse) ProtoMessage() {}

func (x *AcknowledgeAlertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeAlertResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeAlertResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{12}
}

func (x *AcknowledgeAlertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcknowledgeAlertResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{13}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ActiveAlerts  int32                  `protobuf:"varint,2,opt,name=active_alerts,json=activeAlerts,proto3" json:"active_alerts,omitempty"`
	RulesCount    int32                  `protobuf:"varint,3,opt,name=rules_count,json=rulesCount,proto3" json:"rules_count,omitempty"`
	LastUpdate    string                 `protobuf:"bytes,4,opt,name=last_update,json=lastUpdate,proto3" json:"last_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_grpc_proto_alert_alert_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_grpc_proto_alert_alert_proto_rawDescGZIP(), []int{14}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetActiveAlerts() int32 {
	if x != nil {
		return x.ActiveAlerts
	}
	return 0
}

func (x *GetHealthResponse) GetRulesCount() int32 {
	if x != nil {
		return x.RulesCount
	}
	return 0
}

func (x *GetHealthResponse) GetLastUpdate() string {
	if x != nil {
		return x.LastUpdate
	}
	return ""
}

var File_internal_grpc_proto_alert_alert_proto protoreflect.FileDescriptor

const file_internal_grpc_proto_alert_alert_proto_rawDesc = "" +
	"\n" +
	"%internal/grpc/proto/alert/alert.proto\x12\rmirador.alert\"^\n" +
	"\x13ProcessAlertRequest\x12*\n" +
	"\x05alert\x18\x01 \x01(\v2\x14.mirador.alert.AlertR\x05alert\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"^\n" +
	"\x14ProcessAlertResponse\x12F\n" +
	"\x0fprocessed_alert\x18\x01 \x01(\v2\x1d.mirador.alert.ProcessedAlertR\x0eprocessedAlert\"\x87\x03\n" +
	"\x05Alert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bseverity\x18\x02 \x01(\tR\bseverity\x12\x1c\n" +
	"\tcomponent\x18\x03 \x01(\tR\tcomponent\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x128\n" +
	"\x06labels\x18\x06 \x03(\v2 .mirador.alert.Alert.LabelsEntryR\x06labels\x12G\n" +
	"\vannotations\x18\a \x03(\v2%.mirador.alert.Alert.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x0eProcessedAlert\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1e\n" +
	"\n" +
	"escalation\x18\x04 \x01(\tR\n" +
	"escalation\x12$\n" +
	"\rnotifications\x18\x05 \x03(\tR\rnotifications\"3\n" +
	"\x14GetAlertRulesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"G\n" +
	"\x15GetAlertRulesResponse\x12.\n" +
	"\x05rules\x18\x01 \x03(\v2\x18.mirador.alert.AlertRuleR\x05rules\"\x9f\x03\n" +
	"\tAlertRule\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\tR\tcondition\x12\x1a\n" +
	"\bseverity\x18\x05 \x01(\tR\bseverity\x12\x18\n" +
	"\aenabled\x18\x06 \x01(\bR\aenabled\x12<\n" +
	"\x06labels\x18\a \x03(\v2$.mirador.alert.AlertRule.LabelsEntryR\x06labels\x12K\n" +
	"\vannotations\x18\b \x03(\v2).mirador.alert.AlertRule.AnnotationsEntryR\vannotations\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"c\n" +
	"\x16CreateAlertRuleRequest\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.mirador.alert.AlertRuleR\x04rule\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\"G\n" +
	"\x17CreateAlertRuleResponse\x12,\n" +
	"\x04rule\x18\x01 \x01(\v2\x18.mirador.alert.AlertRuleR\x04rule\"g\n" +
	"\x16GetActiveAlertsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\tR\bseverity\"]\n" +
	"\x17GetActiveAlertsResponse\x12,\n" +
	"\x06alerts\x18\x01 \x03(\v2\x14.mirador.alert.AlertR\x06alerts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"w\n" +
	"\x17AcknowledgeAlertRequest\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12'\n" +
	"\x0facknowledged_by\x18\x02 \x01(\tR\x0eacknowledgedBy\x12\x18\n" +
	"\acomment\x18\x03 \x01(\tR\acomment\"N\n" +
	"\x18AcknowledgeAlertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x12\n" +
	"\x10GetHealthRequest\"\x92\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12#\n" +
	"\ractive_alerts\x18\x02 \x01(\x05R\factiveAlerts\x12\x1f\n" +
	"\vrules_count\x18\x03 \x01(\x05R\n" +
	"rulesCount\x12\x1f\n" +
	"\vlast_update\x18\x04 \x01(\tR\n" +
	"lastUpdate2\xc2\x04\n" +
	"\x12AlertEngineService\x12W\n" +
	"\fProcessAlert\x12\".mirador.alert.ProcessAlertRequest\x1a#.mirador.alert.ProcessAlertResponse\x12Z\n" +
	"\rGetAlertRules\x12#.mirador.alert.GetAlertRulesRequest\x1a$.mirador.alert.GetAlertRulesResponse\x12`\n" +
	"\x0fCreateAlertRule\x12%.mirador.alert.CreateAlertRuleRequest\x1a&.mirador.alert.CreateAlertRuleResponse\x12`\n" +
	"\x0fGetActiveAlerts\x12%.mirador.alert.GetActiveAlertsRequest\x1a&.mirador.alert.GetActiveAlertsResponse\x12c\n" +
	"\x10AcknowledgeAlert\x12&.mirador.alert.AcknowledgeAlertRequest\x1a'.mirador.alert.AcknowledgeAlertResponse\x12N\n" +
	"\tGetHealth\x12\x1f.mirador.alert.GetHealthRequest\x1a .mirador.alert.GetHealthResponseBBZ@github.com/platformbuilds/mirador-core/internal/grpc/proto/alertb\x06proto3"

var (
	file_internal_grpc_proto_alert_alert_proto_rawDescOnce sync.Once
	file_internal_grpc_proto_alert_alert_proto_rawDescData []byte
)

func file_internal_grpc_proto_alert_alert_proto_rawDescGZIP() []byte {
	file_internal_grpc_proto_alert_alert_proto_rawDescOnce.Do(func() {
		file_internal_grpc_proto_alert_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_alert_alert_proto_rawDesc), len(file_internal_grpc_proto_alert_alert_proto_rawDesc)))
	})
	return file_internal_grpc_proto_alert_alert_proto_rawDescData
}

var file_internal_grpc_proto_alert_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_grpc_proto_alert_alert_proto_goTypes = []any{
	(*ProcessAlertRequest)(nil),      // 0: mirador.alert.ProcessAlertRequest
	(*ProcessAlertResponse)(nil),     // 1: mirador.alert.ProcessAlertResponse
	(*Alert)(nil),                    // 2: mirador.alert.Alert
	(*ProcessedAlert)(nil),           // 3: mirador.alert.ProcessedAlert
	(*GetAlertRulesRequest)(nil),     // 4: mirador.alert.GetAlertRulesRequest
	(*GetAlertRulesResponse)(nil),    // 5: mirador.alert.GetAlertRulesResponse
	(*AlertRule)(nil),                // 6: mirador.alert.AlertRule
	(*CreateAlertRuleRequest)(nil),   // 7: mirador.alert.CreateAlertRuleRequest
	(*CreateAlertRuleResponse)(nil),  // 8: mirador.alert.CreateAlertRuleResponse
	(*GetActiveAlertsRequest)(nil),   // 9: mirador.alert.GetActiveAlertsRequest
	(*GetActiveAlertsResponse)(nil),  // 10: mirador.alert.GetActiveAlertsResponse
	(*AcknowledgeAlertRequest)(nil),  // 11: mirador.alert.AcknowledgeAlertRequest
	(*AcknowledgeAlertResponse)(nil), // 12: mirador.alert.AcknowledgeAlertResponse
	(*GetHealthRequest)(nil),         // 13: mirador.alert.GetHealthRequest
	(*GetHealthResponse)(nil),        // 14: mirador.alert.GetHealthResponse
	nil,                              // 15: mirador.alert.Alert.LabelsEntry
	nil,                              // 16: mirador.alert.Alert.AnnotationsEntry
	nil,                              // 17: mirador.alert.AlertRule.LabelsEntry
	nil,                              // 18: mirador.alert.AlertRule.AnnotationsEntry
}
var file_internal_grpc_proto_alert_alert_proto_depIdxs = []int32{
	2,  // 0: mirador.alert.ProcessAlertRequest.alert:type_name -> mirador.alert.Alert
	3,  // 1: mirador.alert.ProcessAlertResponse.processed_alert:type_name -> mirador.alert.ProcessedAlert
	15, // 2: mirador.alert.Alert.labels:type_name -> mirador.alert.Alert.LabelsEntry
	16, // 3: mirador.alert.Alert.annotations:type_name -> mirador.alert.Alert.AnnotationsEntry
	6,  // 4: mirador.alert.GetAlertRulesResponse.rules:type_name -> mirador.alert.AlertRule
	17, // 5: mirador.alert.AlertRule.labels:type_name -> mirador.alert.AlertRule.LabelsEntry
	18, // 6: mirador.alert.AlertRule.annotations:type_name -> mirador.alert.AlertRule.AnnotationsEntry
	6,  // 7: mirador.alert.CreateAlertRuleRequest.rule:type_name -> mirador.alert.AlertRule
	6,  // 8: mirador.alert.CreateAlertRuleResponse.rule:type_name -> mirador.alert.AlertRule
	2,  // 9: mirador.alert.GetActiveAlertsResponse.alerts:type_name -> mirador.alert.Alert
	0,  // 10: mirador.alert.AlertEngineService.ProcessAlert:input_type -> mirador.alert.ProcessAlertRequest
	4,  // 11: mirador.alert.AlertEngineService.GetAlertRules:input_type -> mirador.alert.GetAlertRulesRequest
	7,  // 12: mirador.alert.AlertEngineService.CreateAlertRule:input_type -> mirador.alert.CreateAlertRuleRequest
	9,  // 13: mirador.alert.AlertEngineService.GetActiveAlerts:input_type -> mirador.alert.GetActiveAlertsRequest
	11, // 14: mirador.alert.AlertEngineService.AcknowledgeAlert:input_type -> mirador.alert.AcknowledgeAlertRequest
	13, // 15: mirador.alert.AlertEngineService.GetHealth:input_type -> mirador.alert.GetHealthRequest
	1,  // 16: mirador.alert.AlertEngineService.ProcessAlert:output_type -> mirador.alert.ProcessAlertResponse
	5,  // 17: mirador.alert.AlertEngineService.GetAlertRules:output_type -> mirador.alert.GetAlertRulesResponse
	8,  // 18: mirador.alert.AlertEngineService.CreateAlertRule:output_type -> mirador.alert.CreateAlertRuleResponse
	10, // 19: mirador.alert.AlertEngineService.GetActiveAlerts:output_type -> mirador.alert.GetActiveAlertsResponse
	12, // 20: mirador.alert.AlertEngineService.AcknowledgeAlert:output_type -> mirador.alert.AcknowledgeAlertResponse
	14, // 21: mirador.alert.AlertEngineService.GetHealth:output_type -> mirador.alert.GetHealthResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_internal_grpc_proto_alert_alert_proto_init() }
func file_internal_grpc_proto_alert_alert_proto_init() {
	if File_internal_grpc_proto_alert_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_grpc_proto_alert_alert_proto_rawDesc), len(file_internal_grpc_proto_alert_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_grpc_proto_alert_alert_proto_goTypes,
		DependencyIndexes: file_internal_grpc_proto_alert_alert_proto_depIdxs,
		MessageInfos:      file_internal_grpc_proto_alert_alert_proto_msgTypes,
	}.Build()
	File_internal_grpc_proto_alert_alert_proto = out.File
	file_internal_grpc_proto_alert_alert_proto_goTypes = nil
	file_internal_grpc_proto_alert_alert_proto_depIdxs = nil
}
