// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Platform Builds Team",
            "url": "https://github.com/platformbuilds/mirador-core",
            "email": "support@platformbuilds.org"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/kpi/defs": {
            "get": {
                "description": "Retrieve a paginated list of KPI definitions with optional filtering by tags",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kpi-definitions"
                ],
                "summary": "Get KPI definitions",
                "parameters": [
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Filter by tags (comma-separated)",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "maximum": 100,
                        "minimum": 1,
                        "type": "integer",
                        "description": "Maximum number of results (default: 10)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Pagination offset (default: 0)",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_platformbuilds_mirador-core_internal_models.KPIListResponse"
                        }
                    },
                    "400": {
                        "description": "error: invalid query parameters",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: failed to list KPIs",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new KPI definition or update an existing one. If ID is not provided, a new UUID will be generated.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kpi-definitions"
                ],
                "summary": "Create or update KPI definition",
                "parameters": [
                    {
                        "description": "KPI definition payload",
                        "name": "kpi",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_platformbuilds_mirador-core_internal_models.KPIDefinitionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: ok, id: kpi_id",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error: invalid payload or validation error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: failed to upsert KPI",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/kpi/defs/{id}": {
            "delete": {
                "description": "Delete a KPI definition by its ID. Requires confirmation via query parameter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kpi-definitions"
                ],
                "summary": "Delete KPI definition",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KPI definition ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "1",
                            "true",
                            "yes"
                        ],
                        "type": "string",
                        "description": "Confirmation flag (1, true, or yes)",
                        "name": "confirm",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "status: deleted",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "error: missing id or confirmation required",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "error: failed to delete KPI",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_platformbuilds_mirador-core_internal_models.KPIDefinition": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "definition": {
                    "description": "Definition of what the signal means",
                    "type": "string"
                },
                "format": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "kind": {
                    "description": "\"business\" or \"tech\"",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "query": {
                    "description": "JSON query definition",
                    "type": "object",
                    "additionalProperties": true
                },
                "sentiment": {
                    "description": "\"NEGATIVE\", \"POSITIVE\", or \"NEUTRAL\" - increase sentiment",
                    "type": "string"
                },
                "sparkline": {
                    "description": "JSON sparkline config",
                    "type": "object",
                    "additionalProperties": true
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "thresholds": {
                    "description": "JSON thresholds array",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_platformbuilds_mirador-core_internal_models.Threshold"
                    }
                },
                "unit": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "visibility": {
                    "description": "\"private\", \"team\", \"org\"",
                    "type": "string"
                }
            }
        },
        "github_com_platformbuilds_mirador-core_internal_models.KPIDefinitionRequest": {
            "type": "object",
            "properties": {
                "kpiDefinition": {
                    "$ref": "#/definitions/github_com_platformbuilds_mirador-core_internal_models.KPIDefinition"
                }
            }
        },
        "github_com_platformbuilds_mirador-core_internal_models.KPIListResponse": {
            "type": "object",
            "properties": {
                "kpiDefinitions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/github_com_platformbuilds_mirador-core_internal_models.KPIDefinition"
                    }
                },
                "nextOffset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "github_com_platformbuilds_mirador-core_internal_models.Threshold": {
            "type": "object",
            "properties": {
                "color": {
                    "description": "Display color",
                    "type": "string"
                },
                "description": {
                    "description": "Description of the threshold",
                    "type": "string"
                },
                "level": {
                    "description": "e.g., \"warning\", \"critical\"",
                    "type": "string"
                },
                "operator": {
                    "description": "e.g., \"gt\", \"lt\", \"eq\"",
                    "type": "string"
                },
                "value": {
                    "description": "Threshold value",
                    "type": "number"
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "8.0.0",
	Host:             "localhost:8010",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Mirador Core API",
	Description:      "Mirador Core is a comprehensive observability and analytics platform that provides KPI definitions, metrics, logs, traces, and unified queries for monitoring and analyzing system metrics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
