name: ReadTheDocs

on:
  push:
    branches: [ main, master, v7.0.0 ]
    paths:
      - 'docs/**'
      - '.readthedocs.yaml'
      - 'api/openapi.yaml'
      - 'api/openapi.json'
  pull_request:
    branches: [ main, master, v7.0.0 ]
    paths:
      - 'docs/**'
      - '.readthedocs.yaml'
      - 'api/openapi.yaml'
      - 'api/openapi.json'

permissions:
  contents: read

jobs:
  trigger-readthedocs:
    name: Trigger ReadTheDocs Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trigger ReadTheDocs Build
        run: |
          # Check if ReadTheDocs webhook URL is configured
          if [ -n "${RTD_WEBHOOK_URL}" ]; then
            echo "Triggering ReadTheDocs build via webhook..."
            curl -X POST \
              -H "Content-Type: application/json" \
              -d "{\"branches\": [\"v7.0.0\"], \"token\": \"${RTD_TOKEN}\"}" \
              "${RTD_WEBHOOK_URL}"
          else
            echo "ReadTheDocs webhook URL not configured. Please set RTD_WEBHOOK_URL and RTD_TOKEN secrets."
            echo "You can also configure ReadTheDocs to build automatically on pushes to the repository."
            echo "For manual setup instructions, visit: https://docs.readthedocs.io/en/stable/webhooks.html"
          fi
        env:
          RTD_WEBHOOK_URL: ${{ secrets.RTD_WEBHOOK_URL }}
          RTD_TOKEN: ${{ secrets.RTD_TOKEN }}

      - name: Validate Documentation Build
        run: |
          # Install Python and dependencies
          python3 -m pip install --upgrade pip
          python3 -m pip install -r docs/requirements.txt

          # Build documentation locally to validate
          cd docs
          python3 -m sphinx -b html . _build/html -W --keep-going

          echo "Documentation build validation successful!"

      - name: Upload Build Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: docs-build-artifacts
          path: docs/_build/
          retention-days: 7